spring:
  datasource:
    username: root
    password: 57842968
    url: jdbc:mysql://115.159.149.240:3306/calendar?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 115.159.149.240
    port: 6379
  security:
    user:
      name: 1
      password: 1


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.echo.calendar.entity
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8082

jwt:
  config:
    key: iwqjhda8232bjgh432[cicada-smile] #）
    ttl: 21600000 #毫秒

wx:
  appid: wxc63cd1097d2b71c1
  appsecret: 7005887ea25458867a1cc30b3fd69429